language: groovy
before_cache:
- rm -f $HOME/.gradle/caches/*
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

# Using build matrix support to build the sub-projects
env:
  - TEST_DIR=strict-version-matcher-plugin
  - TEST_DIR=oss-licenses-plugin

script: cd $TEST_DIR && gradle assemble && gradle test
